name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_VERSION: 1.12.1

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive
        working-directory: ./terraform

  test-vpc:
    name: Test VPC Module
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        id: init
        run: terraform init -backend=false
        working-directory: ./terraform/modules/vpc

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./terraform/modules/vpc

      - name: Run VPC Module Tests
        id: test
        run: terraform test
        working-directory: ./terraform/modules/vpc

  test-rds:
    name: Test RDS Module
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        id: init
        run: terraform init -backend=false
        working-directory: ./terraform/modules/rds

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./terraform/modules/rds

      - name: Run RDS Module Tests
        id: test
        run: terraform test
        working-directory: ./terraform/modules/rds

  test-ecs:
    name: Test ECS Module
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        id: init
        run: terraform init -backend=false
        working-directory: ./terraform/modules/ecs

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./terraform/modules/ecs

      - name: Run ECS Module Tests
        id: test
        run: terraform test
        working-directory: ./terraform/modules/ecs


